version: 2

jobs:
  build-and-test:

    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run:
          name: Version
          command: bin/logbt --version
      - run:
          name: Current Pattern
          command: bin/logbt --current-pattern
      - run:
          name: Test
          command: bin/logbt --test
      - run:
          name: Unit tests
          command: |
            brew install node
            ./test/unit.sh


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test