version: 2

jobs:
  build-osx:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run:
          name: Version
          command: bin/logbt --version
      - run:
          name: Current Pattern
          command: bin/logbt --current-pattern
      - run:
          name: Test
          command: bin/logbt --test
      - run:
          name: Unit tests
          command: |
            brew update
            brew install node
            brew install coreutils
            echo $PATH
            export PATH=/usr/bin:$PATH
            export PATH=$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}
            which kill
            which cp
            which sleep
            which wait
            which timeout
            which python
            ./test/unit.sh

  build-linux:
    machine: true
    steps:
      - checkout
      - run:
          name: Version
          command: bin/logbt --version
      - run:
          name: Current Pattern
          command: bin/logbt --current-pattern
      - run:
          name: Test
          command: |
           sudo bash -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'
           sudo ./bin/logbt --setup
           bin/logbt --test
      - run:
          name: Unit tests
          command: |
            ./test/unit.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-osx
      - build-linux